# Generated by Django 5.1.4 on 2025-04-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
