# Generated by Django 5.1.4 on 2025-04-14 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0003_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='email',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='image',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='location',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='product',
        ),
        migrations.AddField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migrateflask.item'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
