# Generated by Django 5.1.4 on 2025-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0004_remove_claim_date_remove_claim_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
