# Generated by Django 5.1.4 on 2025-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0006_alter_appuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('product', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='claims/')),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
