# Generated by Django 5.1.4 on 2025-04-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0007_contact_alter_appuser_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactforClaim',
        ),
    ]
