# Generated by Django 5.1.4 on 2025-04-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0008_rename_contact_contactforclaim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactforclaim',
            options={'verbose_name': 'ContactforClaim', 'verbose_name_plural': 'ContactforClaims'},
        ),
    ]
