# Generated by Django 5.1.4 on 2025-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0009_alter_contactforclaim_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
