# Generated by Django 5.1.4 on 2025-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrateflask', '0011_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flask_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
